export const ErrorCodes = {
  NOT_FOUND: 'NOT_FOUND',
  INTERNAL_ERROR: 'INTERNAL_ERROR',
  INVALID_JSON: 'INVALID_JSON',
  UNAUTHORIZED: 'UNAUTHORIZED',
  CODE_REQUIRED: 'CODE_REQUIRED',
  CODE_INVALID_FORMAT: 'CODE_INVALID_FORMAT',
  CODE_NOT_FOUND: 'CODE_NOT_FOUND',
  TOO_MANY_ATTEMPTS: 'TOO_MANY_ATTEMPTS',
  REFRESH_TOKEN_REQUIRED: 'REFRESH_TOKEN_REQUIRED',
  REFRESH_TOKEN_INVALID: 'REFRESH_TOKEN_INVALID',
  INVALID_LOG_EVENT: 'INVALID_LOG_EVENT',
  CORS_FORBIDDEN: 'CORS_FORBIDDEN',
  PERSON_NOT_FOUND: 'PERSON_NOT_FOUND',
  PERSON_VALIDATION_FAILED: 'PERSON_VALIDATION_FAILED',
  PERSON_DELETE_FORBIDDEN: 'PERSON_DELETE_FORBIDDEN',
  PERSON_READ_FOCUS_FORBIDDEN: 'PERSON_READ_FOCUS_FORBIDDEN',
  TREE_FILTER_INVALID: 'TREE_FILTER_INVALID',
} as const;

export type ErrorCode = (typeof ErrorCodes)[keyof typeof ErrorCodes];
